spring.application.name=api-gateway
server.port=8000
logging.level.org.springframework.web=debug
logging.level.org.springframework.cloud.gateway=DEBUG

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# JWT
security.jwt.public-key-path=classpath:keys/public_key.pem

# Disable service discovery
spring.cloud.gateway.discovery.locator.enabled=false

# Define auth-service route 
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/users/**
spring.cloud.gateway.routes[0].filters[0]=PreserveHostHeader

# Define expense-service route
spring.cloud.gateway.routes[1].id=expense-service
spring.cloud.gateway.routes[1].uri=http://expense-service:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/expense/**

# Define auth-openapi route
spring.cloud.gateway.routes[2].id=auth-openapi
spring.cloud.gateway.routes[2].uri=http://auth-service:8080
spring.cloud.gateway.routes[2].predicates[0]=Path=/swagger-docs/auth
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/swagger-docs/auth,/v3/api-docs

# Define expense-openapi route
spring.cloud.gateway.routes[3].id=expense-openapi
spring.cloud.gateway.routes[3].uri=http://expense-service:8081
spring.cloud.gateway.routes[3].predicates[0]=Path=/swagger-docs/expense
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/swagger-docs/expense,/v3/api-docs

# Springdoc OpenAPI configuration
springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/swagger-docs/auth

springdoc.swagger-ui.urls[1].name=Expense Service
springdoc.swagger-ui.urls[1].url=/swagger-docs/expense