spring.application.name=expense-service
server.port=8081

# MySQL
spring.datasource.url=jdbc:mysql://mysql-expense:3306/expensedb
spring.datasource.username=expenseuser
spring.datasource.password=expensepass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
security.jwt.public-key-path=classpath:keys/public_key.pem

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379